---
testing: true
instances:
  - url: https://lemmy.world
    communities:
      - name: news
        posts: 5
      - name: technology
        posts: 3
  - url: https://lemmy.ml
    communities:
      - name: linux
        posts: 2