---
testing: false
image_for_all_posts: true
output_path: ./export/
html: true
port: 9002

# If left on default, user agent will appear as 'Selfhost-Digest/1.0 <Your Network Host Name> https://github.com/c-alex-horton/selfhost-digest'
user_agent_name: default

modules:
  weather:
    location: Denver, Colorado
  lemmy:
    instances:
      - url: https://lemmy.world
        communities:
          - name: news
            posts: 5
          - name: technology
            posts: 3
      - url: https://lemmy.ml
        communities:
          - name: linux
            posts: 2
  rss:
    feeds:
      - url: example.com/feed1
        posts: 5
      - url: example.com/feed2
        posts: 2
