---
testing: false
image_for_all_posts: true
output_path: ./export/
instances:
  - url: https://lemmy.world
    communities:
      - name: news
        posts: 5
      - name: technology
        posts: 3
  - url: https://lemmy.ml
    communities:
      - name: linux
        posts: 2