version: "3.9"

services:
  digest:
    build: .
    ports:
      - "0.0.0.0:9002:9002"
    restart: always
    volumes:
      - ./config.yml:/config.yml:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Chicago
